# Generated by Django 5.1.7 on 2025-03-26 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(default="default.jpg", upload_to="profile_pics/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("rent_month", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("tenant_name", models.CharField(max_length=100)),
                ("house_number", models.CharField(max_length=20)),
                ("flat_number", models.CharField(blank=True, max_length=20, null=True)),
                ("room_no", models.CharField(max_length=20)),
                ("building_name", models.CharField(max_length=100)),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "parking_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "electricity_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "security_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "owner_signature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tenant_signature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                ("date_issued", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Unpaid", "Unpaid"),
                            ("Overdue", "Overdue"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="MainApp.rentinvoice",
                    ),
                ),
            ],
        ),
    ]
