# Generated by Django 5.1.7 on 2025-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
