# Generated by Django 5.1.7 on 2025-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashboard",
            "0002_remove_customuser_address_alter_customuser_mobile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "admin"), ("user", "user")],
                default="user",
                max_length=10,
            ),
        ),
    ]
